services:
  mysql:
    image: mysql:latest
    container_name: mysql_db2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_db2
    ports:
      - "4800:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network_2

  adminer:
    image: adminer
    container_name: adminer_2
    restart: always
    ports:
      - "9001:8080"
    networks:
      - my_network_2

volumes:
  mysql_data:

networks:
  my_network_2:
    driver: bridge
